export const LOVE_REASONS: string[] = [
  "Porque tu sonrisa ilumina mis días",
  "Porque me haces sentir en casa",
  "Porque siempre sabes cómo hacerme reír",
  "Porque tu forma de ver el mundo es única",
  "Porque contigo todo es más bonito",
  "Porque me inspiras a ser mejor persona",
  "Porque tu voz me calma",
  "Porque me haces sentir especial",
  "Porque contigo los días grises tienen color",
  "Porque me encanta tu forma de pensar",

  "Porque tus abrazos lo curan todo",
  "Porque tu risa es contagiosa",
  "Porque haces que todo valga la pena",
  "Porque tu corazón es enorme",
  "Porque me apoyas en todo momento",
  "Porque me haces sentir orgulloso",
  "Porque tu ternura no tiene comparación",
  "Porque cada momento contigo es mágico",
  "Porque eres increíblemente fuerte",
  "Porque haces mi mundo más feliz",

  "Porque contigo el tiempo vuela",
  "Porque tus ojos cuentan historias",
  "Porque me encanta hablar contigo",
  "Porque eres auténtica",
  "Porque tienes una energía hermosa",
  "Porque haces que mi corazón lata más fuerte",
  "Porque eres mi lugar favorito",
  "Porque me haces sentir paz",
  "Porque contigo todo tiene sentido",
  "Porque haces que la vida sea una aventura",

  "Porque me haces sonreír sin razón",
  "Porque tu presencia lo cambia todo",
  "Porque tu dulzura me conquista cada día",
  "Porque eres mi inspiración",
  "Porque haces que los pequeños momentos sean especiales",
  "Porque tu amor es sincero",
  "Porque tienes un alma hermosa",
  "Porque eres única",
  "Porque tu forma de amar es especial",
  "Porque contigo soy feliz",

  "Porque siempre encuentras la manera de sorprenderme",
  "Porque tu cariño es infinito",
  "Porque tu compañía es mi favorita",
  "Porque contigo puedo ser yo mismo",
  "Porque me haces sentir completo",
  "Porque me das paz",
  "Porque tu sonrisa es mi debilidad",
  "Porque me haces creer en el amor",
  "Porque eres maravillosa",
  "Porque me haces sentir afortunado",

  "Porque contigo la vida es más divertida",
  "Porque cada día contigo es especial",
  "Porque me encanta tu forma de ser",
  "Porque haces que todo sea mejor",
  "Porque tu bondad es infinita",
  "Porque siempre estás para mí",
  "Porque me haces sentir amado",
  "Porque tu amor me da fuerza",
  "Porque me haces sentir importante",
  "Porque contigo siempre quiero más",

  "Porque me haces ver la vida diferente",
  "Porque eres increíble",
  "Porque tienes el corazón más bonito",
  "Porque contigo todo fluye",
  "Porque eres luz en mi vida",
  "Porque me haces sentir vivo",
  "Porque cada día me enamoro más de ti",
  "Porque eres mi persona favorita",
  "Porque tu amor me llena",
  "Porque eres todo lo que soñé",

  "Porque haces mi mundo mejor",
  "Porque me haces sentir tranquilo",
  "Porque contigo todo es posible",
  "Porque tu amor me inspira",
  "Porque me haces sentir seguro",
  "Porque eres maravillosa por dentro y por fuera",
  "Porque contigo quiero construir recuerdos",
  "Porque eres mi alegría",
  "Porque me haces sentir especial cada día",
  "Porque eres lo mejor que me ha pasado",

  "Porque tu presencia me hace feliz",
  "Porque me encanta compartir contigo",
  "Porque eres increíblemente dulce",
  "Porque tu amor es puro",
  "Porque haces que cada día valga la pena",
  "Porque eres mi refugio",
  "Porque contigo soy mejor",
  "Porque tu sonrisa es mi favorita",
  "Porque tu amor me hace fuerte",
  "Porque simplemente eres tú",

  "Porque contigo quiero vivir mil historias",
  "Porque haces que todo tenga sentido",
  "Porque eres mi felicidad",
  "Porque tu amor me hace crecer",
  "Porque tu forma de amar es única",
  "Porque eres la razón de muchas sonrisas",
  "Porque tu cariño no tiene límites",
  "Porque contigo siempre quiero más momentos",
  "Porque haces mi vida más bonita",
  "Porque te amo tal como eres",
];
