export const LOVE_REASONS: string[] = [
  "Because your smile lights up my days",
  "Because you make me feel at home",
  "Because you always know how to make me laugh",
  "Because your way of seeing the world is unique",
  "Because everything is more beautiful with you",
  "Because you inspire me to be a better person",
  "Because your voice calms me",
  "Because you make me feel special",
  "Because even gray days have color with you",
  "Because I love your way of thinking",

  "Because your hugs heal everything",
  "Because your laughter is contagious",
  "Because you make everything worthwhile",
  "Because your heart is huge",
  "Because you support me at all times",
  "Because you make me feel proud",
  "Because your tenderness is unmatched",
  "Because every moment with you is magical",
  "Because you are incredibly strong",
  "Because you make my world happier",

  "Because time flies with you",
  "Because your eyes tell stories",
  "Because I love talking to you",
  "Because you are authentic",
  "Because you have beautiful energy",
  "Because you make my heart beat faster",
  "Because you are my favorite place",
  "Because you make me feel peace",
  "Because everything makes sense with you",
  "Because you make life an adventure",

  "Because you make me smile for no reason",
  "Because your presence changes everything",
  "Because your sweetness wins me over every day",
  "Because you are my inspiration",
  "Because you make small moments special",
  "Because your love is sincere",
  "Because you have a beautiful soul",
  "Because you are unique",
  "Because your way of loving is special",
  "Because I am happy with you",

  "Because you always find a way to surprise me",
  "Because your affection is endless",
  "Because your company is my favorite",
  "Because I can be myself with you",
  "Because you make me feel complete",
  "Because you give me peace",
  "Because your smile is my weakness",
  "Because you make me believe in love",
  "Because you are wonderful",
  "Because you make me feel lucky",

  "Because life is more fun with you",
  "Because every day with you is special",
  "Because I love your personality",
  "Because you make everything better",
  "Because your kindness is endless",
  "Because you are always there for me",
  "Because you make me feel loved",
  "Because your love gives me strength",
  "Because you make me feel important",
  "Because I always want more with you",

  "Because you make me see life differently",
  "Because you are amazing",
  "Because you have the most beautiful heart",
  "Because everything flows with you",
  "Because you are light in my life",
  "Because you make me feel alive",
  "Because I fall more in love with you every day",
  "Because you are my favorite person",
  "Because your love fills me",
  "Because you are everything I dreamed of",

  "Because you make my world better",
  "Because you make me feel calm",
  "Because everything is possible with you",
  "Because your love inspires me",
  "Because you make me feel safe",
  "Because you are wonderful inside and out",
  "Because I want to build memories with you",
  "Because you are my joy",
  "Because you make me feel special every day",
  "Because you are the best thing that ever happened to me",

  "Because your presence makes me happy",
  "Because I love sharing with you",
  "Because you are incredibly sweet",
  "Because your love is pure",
  "Because you make every day worthwhile",
  "Because you are my refuge",
  "Because I am better with you",
  "Because your smile is my favorite",
  "Because your love makes me strong",
  "Because you are simply you",

  "Because I want to live a thousand stories with you",
  "Because you make everything make sense",
  "Because you are my happiness",
  "Because your love makes me grow",
  "Because your way of loving is unique",
  "Because you are the reason for many smiles",
  "Because your affection has no limits",
  "Because I always want more moments with you",
  "Because you make my life more beautiful",
  "Because I love you just the way you are",
];
