export const REASONS_PT: string[] = [
  "o teu sorriso ilumina os meus dias",
  "fazes-me sentir em casa",
  "sabes sempre como me fazer rir",
  "a tua forma de ver o mundo é única",
  "tudo é mais bonito contigo",
  "inspiras-me a ser uma pessoa melhor",
  "a tua voz acalma-me",
  "fazes-me sentir especial",
  "até os dias cinzentos têm cor contigo",
  "adoro a tua maneira de pensar",
  "os teus abraços curam tudo",
  "a tua risada é contagiante",
  "fazes tudo valer a pena",
  "o teu coração é enorme",
  "apoias-me em todos os momentos",
  "fazes-me sentir orgulho",
  "a tua ternura não tem comparação",
  "cada momento contigo é mágico",
  "és incrivelmente forte",
  "fazes o meu mundo mais feliz",
  "o tempo voa ao teu lado",
  "os teus olhos contam histórias",
  "adoro conversar contigo",
  "és autêntico",
  "tens uma energia linda",
  "fazes o meu coração bater mais depressa",
  "és o meu lugar favorito",
  "fazes-me sentir paz",
  "tudo faz sentido contigo",
  "transformas a vida numa aventura",
  "fazes-me sorrir sem motivo",
  "a tua presença muda tudo",
  "a tua doçura conquista-me todos os dias",
  "és a minha inspiração",
  "tornas os pequenos momentos especiais",
  "o teu amor é sincero",
  "tens uma alma linda",
  "és único",
  "a tua forma de amar é especial",
  "sou feliz contigo",
  "encontras sempre maneira de me surpreender",
  "o teu carinho não acaba",
  "a tua companhia é a minha preferida",
  "posso ser eu mesmo contigo",
  "fazes-me sentir completo",
  "o teu sorriso é a minha fraqueza",
  "fazes-me acreditar no amor",
  "és maravilhoso",
  "fazes-me sentir sortudo",
  "a vida é mais divertida contigo",
  "cada dia contigo é especial",
  "adoro a tua personalidade",
  "melhoras tudo",
  "a tua bondade não tem fim",
  "estás sempre lá para mim",
  "fazes-me sentir amado",
  "o teu amor dá-me força",
  "fazes-me sentir importante",
  "quero sempre mais contigo",
  "és a melhor coisa que me aconteceu",
];
