export const REASONS_FR: string[] = [
  "ton sourire illumine mes journées",
  "tu me fais me sentir chez moi",
  "tu sais toujours me faire rire",
  "ta façon de voir le monde est unique",
  "tout est plus beau avec toi",
  "tu m'inspires à devenir meilleur",
  "ta voix m'apaise",
  "tu me fais me sentir spécial",
  "même les jours gris ont de la couleur avec toi",
  "j'adore ta façon de penser",
  "tes câlins guérissent tout",
  "ton rire est contagieux",
  "tu donnes du sens à tout",
  "ton cœur est immense",
  "tu me soutiens à chaque instant",
  "tu me rends fier",
  "ta tendresse n'a pas d'égale",
  "chaque moment avec toi est magique",
  "tu es incroyablement fort",
  "tu rends mon monde plus heureux",
  "le temps file à tes côtés",
  "tes yeux racontent des histoires",
  "j'adore parler avec toi",
  "tu es authentique",
  "tu as une énergie magnifique",
  "tu fais battre mon cœur plus vite",
  "tu es mon endroit préféré",
  "tu m'apportes la paix",
  "tout a du sens avec toi",
  "tu transformes la vie en aventure",
  "tu me fais sourire sans raison",
  "ta présence change tout",
  "ta douceur me conquiert chaque jour",
  "tu es mon inspiration",
  "tu rends les petits moments spéciaux",
  "ton amour est sincère",
  "tu as une belle âme",
  "tu es unique",
  "ta façon d'aimer est spéciale",
  "je suis heureux avec toi",
  "tu trouves toujours le moyen de me surprendre",
  "ta tendresse est sans fin",
  "ta compagnie est ma préférée",
  "je peux être moi-même avec toi",
  "tu me rends complet",
  "ton sourire est ma faiblesse",
  "tu me fais croire en l'amour",
  "tu es merveilleux",
  "tu me fais me sentir chanceux",
  "la vie est plus drôle avec toi",
  "chaque jour avec toi est spécial",
  "j'adore ta personnalité",
  "tu rends tout meilleur",
  "ta gentillesse n'a pas de limites",
  "tu es toujours là pour moi",
  "tu me fais me sentir aimé",
  "ton amour me donne de la force",
  "tu me fais me sentir important",
  "j'en veux toujours plus avec toi",
  "tu es la meilleure chose qui me soit arrivée",
];
