export const REASONS_ES: string[] = [
  "tu sonrisa ilumina mis días",
  "me haces sentir en casa",
  "siempre sabes cómo hacerme reír",
  "tu manera de ver el mundo es única",
  "todo es más bonito contigo",
  "me inspiras a ser mejor persona",
  "tu voz me calma",
  "me haces sentir especial",
  "hasta los días grises tienen color contigo",
  "me encanta tu forma de pensar",
  "tus abrazos lo curan todo",
  "tu risa es contagiosa",
  "haces que todo valga la pena",
  "tu corazón es enorme",
  "me apoyas en todo momento",
  "me haces sentir orgullo",
  "tu ternura no tiene comparación",
  "cada momento contigo es mágico",
  "eres increíblemente fuerte",
  "haces mi mundo más feliz",
  "el tiempo vuela a tu lado",
  "tus ojos cuentan historias",
  "me encanta hablar contigo",
  "eres auténtico",
  "tienes una energía preciosa",
  "haces que mi corazón lata más rápido",
  "eres mi lugar favorito",
  "me haces sentir paz",
  "todo tiene sentido contigo",
  "conviertes la vida en una aventura",
  "me haces sonreír sin motivo",
  "tu presencia lo cambia todo",
  "tu dulzura me conquista cada día",
  "eres mi inspiración",
  "conviertes los pequeños momentos en especiales",
  "tu amor es sincero",
  "tienes un alma hermosa",
  "eres único",
  "tu forma de amar es especial",
  "soy feliz contigo",
  "siempre encuentras la manera de sorprenderme",
  "tu cariño no se acaba",
  "tu compañía es mi favorita",
  "puedo ser yo mismo contigo",
  "me haces sentir completo",
  "tu sonrisa es mi debilidad",
  "me haces creer en el amor",
  "eres maravilloso",
  "me haces sentir afortunado",
  "la vida es más divertida contigo",
  "cada día contigo es especial",
  "me encanta tu personalidad",
  "haces todo mejor",
  "tu bondad no tiene fin",
  "siempre estás ahí para mí",
  "me haces sentir amado",
  "tu amor me da fuerza",
  "me haces sentir importante",
  "siempre quiero más contigo",
  "eres lo mejor que me ha pasado",
];
