// Reason endings; the language prefix ("Because", "Porque"...) is added in generateReasons.
export const REASONS_EN: string[] = [
  "your smile lights up my days",
  "you make me feel at home",
  "you always know how to make me laugh",
  "your way of seeing the world is unique",
  "everything is more beautiful with you",
  "you inspire me to be a better person",
  "your voice calms me",
  "you make me feel special",
  "even gray days have color with you",
  "I love your way of thinking",
  "your hugs heal everything",
  "your laughter is contagious",
  "you make everything worthwhile",
  "your heart is huge",
  "you support me at all times",
  "you make me feel proud",
  "your tenderness is unmatched",
  "every moment with you is magical",
  "you are incredibly strong",
  "you make my world happier",
  "time flies with you",
  "your eyes tell stories",
  "I love talking to you",
  "you are authentic",
  "you have beautiful energy",
  "you make my heart beat faster",
  "you are my favorite place",
  "you make me feel peace",
  "everything makes sense with you",
  "you make life an adventure",
  "you make me smile for no reason",
  "your presence changes everything",
  "your sweetness wins me over every day",
  "you are my inspiration",
  "you make small moments special",
  "your love is sincere",
  "you have a beautiful soul",
  "you are unique",
  "your way of loving is special",
  "I am happy with you",
  "you always find a way to surprise me",
  "your affection is endless",
  "your company is my favorite",
  "I can be myself with you",
  "you make me feel complete",
  "you give me peace",
  "your smile is my weakness",
  "you make me believe in love",
  "you are wonderful",
  "you make me feel lucky",
  "life is more fun with you",
  "every day with you is special",
  "I love your personality",
  "you make everything better",
  "your kindness is endless",
  "you are always there for me",
  "you make me feel loved",
  "your love gives me strength",
  "you make me feel important",
  "I always want more with you",
  "you make me see life differently",
  "you are amazing",
  "you have the most beautiful heart",
  "everything flows with you",
  "you are light in my life",
  "you make me feel alive",
  "I fall more in love with you every day",
  "you are my favorite person",
  "your love fills me",
  "you are everything I dreamed of",
  "you make my world better",
  "you make me feel calm",
  "everything is possible with you",
  "your love inspires me",
  "you make me feel safe",
  "you are wonderful inside and out",
  "I want to build memories with you",
  "you are my joy",
  "you make me feel special every day",
  "you are the best thing that ever happened to me",
  "your presence makes me happy",
  "I love sharing with you",
  "you are incredibly sweet",
  "your love is pure",
  "you make every day worthwhile",
  "you are my refuge",
  "I am better with you",
  "your smile is my favorite",
  "your love makes me strong",
  "you are simply you",
  "I want to live a thousand stories with you",
  "you make everything make sense",
  "you are my happiness",
  "your love makes me grow",
  "your way of loving is unique",
  "you are the reason for many smiles",
  "your affection has no limits",
  "I always want more moments with you",
  "you make my life more beautiful",
  "I love you just the way you are"
];
